version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5024:5024"
    volumes:
      - .:/app
      - my-flask-app-data:/app/data
    env_file:
      - .env
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:5024", "app:app"]
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
        - "127.0.0.1:27017:27017"
    volumes:
      - my-db-data:/data/db
    env_file:
      - .env

volumes:
  my-flask-app-data:
  my-db-data:
